#!/bin/bash
# Purpose: rewrites the atDNA combined output CSV file in pseudo AncestryDNA v2 format
#
# Author:  A.Robers 2020-01-05
# License: GPLv3. See accompanying LICENSE file.
# No warranty. You are responsible for your use of this program.

DTT=`date -u '+%d/%m/%Y %H:%M:%S'`
DMY=`date -u '+%Y-%m-%d'`
start=`date +%s`
SNPS=0
i=0
OUTFL="AncestryDNA.txt"
ZIPFL="Ancestry_MyFile-TST_dna-data-$DMY.zip"

# Run sed once on the combined file, or once per line (takes ages).
# 1 = File level, 0 = Line level
SED_TYPE=1

echo

if [ $# = 0 -o $# -gt 3 ]
then
  echo "Usage:   `basename $0` <combined_file.csv> [<outputAncestryFromatFileName> [<outputAncestryFromatArchive>]]"
  echo
  echo "Purpose: Reformats, and packages the atDNA combined output CSV file, in AncestryDNA v2 format; to humour utilities that expect that format."
  echo
  echo "defaults: "
  echo "  outputAncestryFromatFileName = $OUTFL"
  echo "  outputAncestryFromatArchive  = $ZIPARC"
  echo
  exit 1
fi

if [ ! -f $1 ]
then
  echo "Error: Not a file - $1"
  exit 2
fi
INFILE=$1
SNPS=`wc -l ${INFILE}|awk -F' ' '{print $1}'`

if [ $SNPS -lt 2 ]
then
  echo "Error: file empty"
  exit 3
fi

if [ $# = 2 ]
then 
  OUTFL=$2
fi

if [ $# = 3 ]
then
  ZIPFL=$3
fi

echo "reading $1"
echo "output will be witten to: $OUTFL"
echo "and packaged into: $ZIPFL"
echo
echo "Input file Stats:"
echo " - line count: $SNPS"
echo
echo " - SNPs per Chromosome:"
cut -d, -f2 $INFILE | uniq -c
echo
end=`date +%s`
echo "Runtime: $(($end - $start)) seconds"

echo "#AncestryDNA raw data download
#This file was generated by AncestryDNA at: $DTT UTC
#Data was collected using AncestryDNA array version: V2.0
#Data is formatted using AncestryDNA converter version: V1.0
#Below is a text version of your DNA file from Ancestry.com DNA, LLC.  THIS 
#INFORMATION IS FOR YOUR PERSONAL USE AND IS INTENDED FOR GENEALOGICAL RESEARCH 
#ONLY.  IT IS NOT INTENDED FOR MEDICAL, DIAGNOSTIC, OR HEALTH PURPOSES.  THE EXPORTED DATA IS 
#SUBJECT TO THE AncestryDNA TERMS AND CONDITIONS, BUT PLEASE BE AWARE THAT THE 
#DOWNLOADED DATA WILL NO LONGER BE PROTECTED BY OUR SECURITY MEASURES.
#WHEN YOU DOWNLOAD YOUR RAW DNA DATA, YOU ASSUME ALL RISK OF STORING, 
#SECURING AND PROTECTING YOUR DATA.  FOR MORE INFORMATION, SEE ANCESTRYDNA FAQS. 
#
#Genetic data is provided below as five TAB delimited columns.  Each line 
#corresponds to a SNP.  Column one provides the SNP identifier (rsID where 
#possible).  Columns two and three contain the chromosome and basepair position 
#of the SNP using human reference build 37.1 coordinates.  Columns four and five 
#contain the two alleles observed at this SNP (genotype).  The genotype is reported 
#on the forward (+) strand with respect to the human reference.
rsid    chromosome      position        allele1 allele" > $OUTFL

if [ $SED_TYPE ]
then
  sed -e "/^RSID/d" -e "s/,Y,/,24,/" -e "s/,\([ACTG]\)\([ACTG]\)/,\1,\2/" -e 's/,/	/g' $INFILE >> $OUTFL
else 
  echo "This will take some time ..."
  echo
  while IFS= read -r line 
  do
    i=$((i+1))
    echo $line | sed -e "/^RSID/d" -e "s/,Y,/,24,/" -e "s/,\([ACTG]\)\([ACTG]\)/,\1,\2/" -e 's/,/	/g' >> $OUTFL
    echo -ne "SNP processed: $i\r"
  done < $INFILE
fi

echo
end=`date +%s`
echo "Runtime: $(($end - $start)) seconds"
echo
echo "zipping up into: $ZIPFL"
zip -r $ZIPFL $OUTFL
unzip -l $ZIPFL
echo
end=`date +%s`
echo "Runtime: $(($end - $start)) seconds"
